spring:
  datasource:
    master:
      dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

#      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      maxConnections: 100
      waitTimeout: 10000
      hikari:
        maximumPoolSize: 10
        maxTotal: 100
        maxWaitMills: 10000
        maxIdle: 100
        idleTimeout: 10000
        testOnBorrow: true
        validationInterval: 34000
        validationQuery: SELECT 1
      tomcat:
        initial-size: 5
        max-total: 100
        max-wait-mills: 10000
        min-idle: 10
        test-on-borrow: true
        validation-query: SELECT 1

    slave:
      dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

#      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      maxConnections: 100
      waitTimeout: 10000
      hikari:
        maximumPoolSize: 10
        maxTotal: 100
        maxWaitMills: 10000
        maxIdle: 100
        idleTimeout: 10000
        testOnBorrow: true
        validationInterval: 34000
        validationQuery: SELECT 1
      tomcat:
        initial-size: 5
        max-total: 100
        max-wait-mills: 10000
        min-idle: 10
        test-on-borrow: true
        validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
    parser:
      ALLOW_UNQUOTED_CONTROL_CHARS: true
    #    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

---
spring:
  profiles: local
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/db_notice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      hikari:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/db_notice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password:
    slave:
      url: jdbc:mysql://localhost:3306/db_notice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      hikari:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/db_notice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password:

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
